import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Elements} from '@stripe/react-stripe-js';
import { loadStripe } from '@stripe/stripe-js';
import PaymentCard from '../component/paymentCard';


export default function Home() {
 
  const stripePromise = loadStripe('pk_test_51JW2AbE8Ae2Mwo9G2u5DX0rwlFZVyQGDanFTdU9yWc1cUw2Tt5SaCxbAMLY7HO9sucMmJBKcs9MFPXIMXk5gxhbJ00kCf66Lzh');

 

 
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Elements stripe={stripePromise}>
     <PaymentCard/>
      </Elements>
    </div>
  )
}
